Enviorment setup
murphan/ALife pull request #2
Opened 2022-12-01 06:31 UTC by murphan

Controller and map base classes. The step function updates the entire map and everything on it.

2023-01-18 00:55 UTC, balduvian commented
For the environment, I think that the map of cells should be a 1D vector. 1D vectors have a lot of advantages, including being easier to create, having less memory to "manage", and being more efficient, since all memory is allocated contiguously. We just need to store a width and a height for the map, and then use the index `y * width + x` to get the cell at `x, y`. We can create helper functions to get these indices. The inverse of this equation, to start with the index and get the x and y value is `x = i % width; y = i / width` (with integer division). I've used this pattern very many times before (and I've even used it for storing the bodies of the organisms, so I think it would be a good fit here.

We should also have the environment constructor take a width and a height for more size customization instead of it always being square.

Inside MapCell, the temperature and light environment factors should probably be put into an array, since later we're going to have 4 of them and it will be easier to access them by index (we can name the indices in an enum). When I say array here I literally mean stack array, not vector, since there's a fixed number of environment variables. Depending on how we want to implement how many food can be on a single square, we could have the food be in a fixed stack array too for extra efficiency. But I would like to talk about the food system more because there's a lot of interesting ways we could go about it.

2023-01-18 01:02 UTC, balduvian requested changes
I left a comment before this review lol, I should've done it in here.

2023-01-18 01:02 UTC, balduvian commented on src/Environment/Environment.h
> +            std::vector<std::vector<MapCell>> map;  //2d Vector of each cell in the map
map would be better as a 1D array, using indices math to access it

2023-01-18 01:02 UTC, balduvian commented on src/Environment/Environment.cpp
> +Environment::Environment(int startCells) {
we can see that when you have vectors of vectors, you need all of this initialization code. Most of this could be reduced to only one constructor call for the map in 1 dimension.

2023-01-18 01:02 UTC, balduvian commented on src/Environment/MapCell.h
> +    public:
MapCell should probably have a default constructor so it can be created fast in a default state when we initialize the map array

2023-01-18 01:02 UTC, balduvian commented on src/Environment/MapCell.h
> +        int getTemperature();
if we make all the factors an array `int factors[4]`, we can use one accessor function that takes in the index of the factor we want. Somewhere else make an enum with `TEMPERATURE, LIGHT, PLACEHOLDER0, PLACEHOLDER1`. We can figure out what the rest of the factors will be called later.

2023-01-19 04:59 UTC, hudkinsnoah reviewed
I agree with Emmett's comments. Other than that though, it looks good!

2023-02-04 04:57 UTC, balduvian approved these changes
Looks good let's get this in

2023-02-04 05:00 UTC, merged